app/main/__init__.py
from flask import Blueprint
from app.data.models import Permission


main = Blueprint('main', __name__, template_folder='templates')

from . import views

@main.app_context_processor
def inject_permissions():
	return dict(Permission=Permission)

app/main/views.py
import os

from flask import render_template, send_from_directory, request, json, jsonify, redirect, url_for, flash
from app import app, db
from app.main import main
# from app.cache import cache
from sqlalchemy.sql import func
from flask_login import current_user, login_required
from app.data.models import Permission, Advert, ShoppingCart, Date_available, Experience, Flyer, Imageexp, Image, Rating, Shop, Slideshow, Story, Item, StorySchema, ItemSchema, User, Review, SlideshowMobile, Category, Hosty, Comment, Book
from flask_mail import Message
from app.email import send_email
from app.form.forms import ExperienceForm, SearchForm, ContactForm, HostForm, CommentForm, BookForm
from app import mail
from app.decorators import admin_required, permission_required
from app.shopping_cart.ShoppingCart import Shopping_Cart
from flask_admin import Admin, form
from app import db
from flask_restful import reqparse
#from flask_security.decorators import roles_required
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.orm.exc import MultipleResultsFound
from sqlalchemy.exc import IntegrityError

from werkzeug import secure_filename

#import beyonic

# image routes

# creating thumnailfolder
# thumbnail_path = app.config['RESIZE_ROOT']
# try:
#     os.mkdir(thumbnail_path)
# except OSError:
#     pass

# This snippet is in public domain.
# However, please retain this link in your sources:
# http://flask.pocoo.org/snippets/120/
# Danya Alexeyevsky
from flask import Flask, render_template, request
from flask_sqlalchemy import SQLAlchemy


from flask import session, redirect, current_app, g
import functools
from datetime import datetime

@main.before_app_request
def before_request():
    # if current_user.is_authenticated:
    #     current_user.last_seen = datetime.utcnow()
    #     db.session.commit()
    g.search_form = SearchForm()

@main.context_processor
def inject_cart_count():
    if current_user.is_anonymous:
        count = 0
    else:
        count = ShoppingCart.query.filter_by(user_id=current_user.id).count()
    return dict(count=count)


def redirect_url(default='main.index'):
    return request.args.get('next') or \
           request.referrer or \
           url_for(default)


# def parse_arg_from_requests(arg, **kwargs):
#     parse = reqparse.RequestParser()
#     parse.add_argument(arg, **kwargs)
#     args = parse.parse_args()
#     return args[arg]

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


@main.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory(app.config['SLIDES'], filename)

@main.route('/experienceimg/<filename>')
def uploaded_experience(filename):
    return send_from_directory(app.config['EXPERIENCES'],filename)

@main.route('/shopimg/<filename>')
def uploaded_item(filename):
    return send_from_directory(app.config['SHOP'],filename)

@main.route('/flyer/<filename>')
def uploaded_flyer(filename):
    return send_from_directory(app.config['FLYERS'],filename)

@main.route('/advert2/<filename>')
def uploaded_advert(filename):
    return send_from_directory(app.config['ADVERTS'],filename)

@main.route('/storyimg/<filename>')
def uploaded_story(filename):
    return send_from_directory(app.config['STORIES'],filename)


@main.route("/message")
def message():

    msg = Message("Hello",
                  sender="from@example.com",
                  recipients=["quinton.ssebaggala@gmail.com"])
    msg.body = "testing"
    msg.html = "<b>testing</b>"

    return mail.send(msg)

@main.route('/')
# @anchor
# @login_required
# @admin_required
# @cache.cached(300, key_prefix='index')
def index():
    slideshow = Slideshow.query.order_by(Slideshow.created_on.desc()).limit(3).all()
    slideshowMobile = SlideshowMobile.query.order_by(SlideshowMobile.created_on.desc()).limit(3).all()
    # stories = Story.query.order_by(Story.created_on.desc()).limit(12).all()
    experience = Imageexp.query.order_by(Imageexp.created_on.desc()).limit(8).all()
    shop = Shop.query.order_by(Shop.created_on.desc()).limit(12).all()
    flyers = Flyer.query.order_by(Flyer.created_on.desc()).limit(2).all()
    adverts = Advert.query.order_by(Advert.created_on.desc()).limit(3).all()
    trend = Imageexp.query.filter_by(trend=True).limit(8).all()
    story = Story.query.all()
    # all_products = Category.query.filter_by(id=category_id).first().experiences
    # cache.delete('detail')
    return render_template('main/main.html', slideshow=slideshow, experience=experience,
        shop=shop, flyers=flyers, adverts=adverts, trend=trend, slideshowMobile=slideshowMobile, story=story)


@main.route('/test')
def test():
    data = Experience.query.order_by(Experience.created_on.desc()).limit(5).all()
    return render_template('test.html', data=data)

@main.route('/shop/')
@main.route('/shop/<int:itemid>', methods = ['GET'])
# @login_required
# @permission_required(Permission.FOLLOW)
def shop(itemid = 0):
    page_num = int(request.args.get('page', 1))
    # shop = Shop.query.order_by(Shop.created_on.desc()).limit(12).all()
    shop = Shop.query.order_by(Shop.created_on.desc()).paginate(page=page_num, per_page=100, error_out=True)
    item = Shop.query.get(itemid)
    return render_template('main/shop.html', shop=shop, item=item)

# @main.context_processor
# def example():
#     return dict(myexample='This is an example')

@main.route('/experience/')
# @anchor
# @login_required
# @permission_required(Permission.FOLLOW)
def experience():
    page_num = request.args.get('page', 1, type=int)
    # shop = Shop.query.order_by(Shop.created_on.desc()).limit(12).all()
    experience = Imageexp.query.order_by(Imageexp.created_on.desc()).paginate(page=page_num, per_page=12, error_out=True)
    return render_template('main/experiences.html', experience=experience)


# @main.route('/add_experience/')
# def add_experience():
#     experience = Experience()
#     return render_template('test.html', data=data)


@main.route('/host/', methods=['GET', 'POST'])
def host():
    host = Hosty()
    form = HostForm()
    if request.method == 'POST':
        # form = ExperienceForm(request.form)
        form.populate_obj(host)
        try:
            db.session.add(host)
            #db.session.commit()
            db.session.commit()
            flash('thank you', 'success')
            return redirect(url_for('main.index'))
            db.session.add(host)
            #db.session.commit()
            db.session.commit()
            
        except:
            session.rollback()
            raise
            flash("Please try again or contact us")
    return render_template('main/host.html', form=form)

@main.route('/becomeahost/', methods=['GET'])
#@roles_required('admin')
def become_a_host():
    return render_template('main/host_landing.html')

@main.route('/help/')
# @anchor
def help():
    return render_template('main/help.html')



@main.route('/detail', methods=['GET'])
# @cache.cached(300, key_prefix='detail')
def detail():
    experience_id = request.args.get('id')
    experience = Experience.query.filter_by(id=experience_id).first()
    comments = Comment.query.filter_by(experience_id=experience_id).all()
    # cache.delete('index')
    return render_template('main/experience_detail.html', experience=experience)


@main.route('/rating', methods=['POST'])
@login_required
@permission_required(Permission.FOLLOW)
def rating():
    # data = request.get_json(force=True)
    # id= parse_arg_from_requests('exp_id')
    exp_id = request.json['exp_id']
    rating = request.json['rating']
    user_id = current_user.id
    rate_count = []
    reviews_count = []

    query = Experience.query.join(Experience.users).filter(
     Experience.id == exp_id,
     User.id == user_id
    )

    query2 = Review.query.filter_by(
     exp_id=exp_id,
     rate=rating
    )

    experience=Experience.query.get_or_404(exp_id)
    user = User.query.get_or_404(user_id)
    vote = Rating.query.filter_by(rating=rating).first()
    review_exit = query2.first()


    try:
        experiences = query.one()
        print('available')
    except MultipleResultsFound as e:
        print (e)
        # Deal with it
    except NoResultFound as e:
        print (e)
        experience.users.append(user)
        if review_exit:
            # review_exit.review_num =+reviews_number
            review_exit.review_num = Review.review_num + 1
        else:
            experience.rates.append(vote)
            review = Review(exp_id=exp_id, rate=rating, review_num=1)
            rate =  Rating.query.filter_by(rating=rating).first()
            rate.reviews.append(review)
        try:
            db.session.commit()
        except IntegrityError as e:
            app.logger.error(e)
            db.session.rollback()

    review_row = Review.query.filter_by(exp_id=exp_id).all()
    # calculating weighted average
    for a in review_row:
        rate_count.append(a.rate)
        reviews_count.append(a.review_num)
    average = sum(x * y for x, y in zip(rate_count, reviews_count)) / sum(reviews_count)
    # updating Weighted_Average column
    experience.Weighted_Average = average
    experience.reviews_no = sum(reviews_count)
    db.session.commit()

    return json.dumps({'status': 'OK', 'rating': rating, 'id': exp_id, 'user': user_id})
    # return redirect( url_for('main.review'))

@main.route('/review', methods=['POST','Get'])
@login_required
#@permission_required(Permission.FOLLOW)
def review():
    rate = request.args.get('rate')
    exp_id = request.args.get('exp_id')
    form = CommentForm()
    comments = Comment.query.filter_by(experience_id=exp_id).all()
    # experience = Experience.query.filter_by(users=exp_id).first()
    # experience = User.query.get(current_user.id).users
    # experience = Experience.query.join(User).filter(User.id == current_user.id, Experience.id == exp_id)

app/main/templates/main/_shop.html
<div class="col-md-4 col-lg-2 pt-0 pb-0 mb-1 mt-1">
	<div class="card d-block w-100 border-0">
		<a role="button" class="link-reset" href="{{ url_for('main.experience) }}'">
		<div class="tubayo-shop-slide h-auto w-100" >
			<img class="card-img-top rounded img-fluid h-auto w-100" src="{{ url_for('main.uploaded_item', filename=item.filename) }}" alt="{{ item.filename }}">
		</div>
		</a>
		<a role='button' class="link-reset" href="{{ url_for('main.experience', id=item.id)}}" data-toggle="modal" data-target="#exampleModalCenter {{ url_for('main.shop', id=item.id)}}">
			<div class="card-body px-0 py-1 text-center">
				<p class="mb-1 text-bold-md">{{ item.item_name}}</p>
				<p class="mb-0 text-small-faint">${{item.price}}</p>
			</div>
		</a>
	</div>
</div>

app/main/templates/main/main.html
{% extends 'main/index.html' %}

{% block header %}
<header>
	<div id="carouselTubayoIndicators" class="carousel slide d-none d-sm-none d-md-block" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselTubayoIndicators" data-slide-to="0" class="active"></li>
			<li data-target="#carouselTubayoIndicators" data-slide-to="1"></li>
			<li data-target="#carouselTubayoIndicators" data-slide-to="2"></li>
		</ol>
		<a href="{{ url_for('main.experience')}}">
		<div class="carousel-inner" role="listbox">
			{% for slideshow in slideshow %}
			
			<div class="carousel-item carousel-height{% if loop.index == 1 %} active{% endif %}" style="background-image: url('{{ url_for('main.uploaded_file', filename=slideshow.filename) }}');">			  
			</div>
			{% endfor %}
		</div></a>
		<a class="carousel-control-prev" href="#carouselTubayoIndicators" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselTubayoIndicators" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<!-- mobile -->
	<div id="carouselTubayomobileIndicators" class="carousel slide mobile d-block d-sm-block d-md-none d-lg-none d-xl-none" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselTubayomobileIndicators" data-slide-to="0" class="active"></li>
			<li data-target="#carouselTubayomobileIndicators" data-slide-to="1"></li>
			<li data-target="#carouselTubayomobileIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			{% for slideshow in slideshowMobile %}
			<div class="carousel-item carousel-mobile-height{% if loop.index == 1 %} active{% endif %}" style="background-image: url('{{ url_for('main.uploaded_file', filename=slideshow.filename) }}');">		  
			</div>
			{% endfor %}
		</div>
		<a class="carousel-control-prev" href="#carouselTubayomobileIndicators" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselTubayomobileIndicators" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
</header>
{% endblock %}

{% block stories %}
{%if story %}
	<section id="stories">
		<h3 class="pb-1 mb-2 font-weight-bold border-bottom">
			<div class="clearfix">
				<h3 class="float-left mt-3">Tubayo Stories</h3>
			</div>
		</h3>
		<div class="d-flex align-items-center pb-0 mb-0 text-white-50 bg-white">
			<div id="stories" class="text-primary"></div>
		</div>
	</section>
{% endif %}
{% endblock %}

{% block experiences %}
{%if experience %}
	<section id="experiences">
		<h3 class="pb-1 mb-2 mt-2 font-weight-bold border-bottom">
			<div class="clearfix">
				<h3 class="float-left">Top Rated Experiences</h3>
				<a role="button" href="{{ url_for('main.experience') }}" class="btn btn-link float-right text-primary">see all <i class="fa fa-angle-right"></i></a>
			</div>
		</h3>

		<div class="py-3">
			<div class="row equal">
				{% for experience in experience %}

				<div class="col-md-6 col-lg-3 pt-0 pb-0 mb-1 mt-1">
					<a class="link-reset" href="{{ url_for('main.detail', id=experience.experience_id)}}">
						<div class="card mb-1 mt-1 border-0 h-100">
							<div class="tubayo-experience-img tubayo-experiencemobile-img w-100 ">
								<!-- <i class="fas fa-heart topright"></i> -->
								<img class="card-img-top rounded img-fluid h-100" src="{{ url_for('main.uploaded_experience', filename=experience.image.filename) }}" alt="Card image cap">
							</div>
							<div class="card-body px-0 py-1">
								<p class="mb-1 card-text text-uppercase text-small">{{ experience.experience.experience_title }} · <span>{{experience.experience.place}}</span></p>
								<p class="mb-1 text-bold-md">{{ experience.experience.tag }}</p>
								<p class="mb-0 text-small-faint">USD {{ experience.experience.price }} per person</p>

								<div class="mb-0 mt-0 d-flex justify-content-between align-items-center">
									<span class="rateYo pl-0"><input type="hidden" value="{{ experience.experience.Weighted_Average }}" name="rateyoid" class="rateyoid"></span>
									<span class="review float-left" aria-label="{{ experience.experience.reviews_no }} reviews">
										<span class="reviews">{{ experience.experience.reviews_no }}</span>
									</span>
								</div>

							</div>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
			<a role="button" href="{{ url_for('main.experience')}}" class="btn btn-link float-right text-primary">see all experiences <i class="fa fa-angle-right"></i></a>
		</div>
	</section>
{% endif %}
{% endblock %}
{% block shop %}
{%if shop %}
	<section id="shop">
		<h3 class="pb-1 mb-2 font-weight-bold border-bottom">
			<div class="clearfix">
				<h3 class="float-left">Top destinations </h3>
				
			</div>
		</h3>
		<div class="py-2">
			<div class="row equal">
				<div id="tubayoCarousel" class="carousel slide w-100" data-ride="carousel">
					<div class="carousel-inner tubayo-carousel-inner w-100" role="listbox">
						{% for experience in experience %}
						<div class="carousel-item {% if loop.index == 1 %} active{% endif %}">
							<div class="card d-block col-3 w-100 border-0">
								<div class="tubayo-shop-slide h-auto w-100">
									<img class="card-img-top rounded img-fluid h-100" src="{{ url_for('main.uploaded_experience', filename=experience.image.filename) }}" alt="Card image cap">
								</div>
								<a class="link-reset" href="{{ url_for('main.shop', place = experience.experience.place) }}">
									<div class="card-body px-0 py-1 text-center">
										<p class="mb-1 text-bold-md">{{ experience.experience.place }}</p>
										<!--<p class="mb-0 text-small-faint">USD {{ experience.experience.price }} per person</p>-->
									</div>
								</a>
							</div>
						</div>
						{% endfor %}
					</div>
					<a class="carousel-control-prev" href="#tubayoCarousel" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#tubayoCarousel" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
			<!--<a role="button" href="{{ url_for('main.experience')}}" class="btn btn-link float-right text-primary">see all <i class="fa fa-angle-right"></i></a> -->
		</div>
	</section>
{% endif %}
{% endblock %}

{% block flyer %}
	{%if flyer %}
		<section id="flyer" class="pt-5 {% if not flyers%} d-none {% endif %}">
			<div class="row equal">
				{% for flyer in flyers %}
				
				<div class="col-sm-10 col-md-6 pb-3">
					<div class="card h-auto w-100">
						
						<img class="card-img tubayo-flyer-img w-100" src="{{ url_for('main.uploaded_flyer', filename=flyer.filename) }}" alt="Card image">
					</div>
				</div></div></a>
				{% endfor %}
			</div>
		</section>
	{% endif %}
{% endblock %}

{% block tubayotrend %}
	{% if trend %}
		<section id="tubayo-trend">
			<h3 class="pb-1 mb-2 mt-2 font-weight-bold border-bottom">
				<div class="clearfix">
					<h3 class="float-left">Recommended Experiences</h3>
				</div>
			</h3>

			<div class="py-2">
				<div class="row equal">
					{% for experience in trend %}

					<div class="col-md-6 col-lg-3 pt-0 pb-0 mb-1 mt-1">
						<a class="link-reset" href="{{ url_for('main.detail', id=experience.experience_id)}}">
							<div class="card mb-1 mt-1 border-0 h-100">
								<div class="tubayo-experience-img tubayo-experiencemobile-img w-100 ">
									<i class="fas fa-heart topright"></i>
									<img class="card-img-top rounded img-fluid h-100" src="{{ url_for('main.uploaded_experience', filename=experience.image.filename) }}" alt="Card image cap">
								</div>
								<div class="card-body px-0 py-1">
									<p class="mb-1 card-text text-uppercase text-small">{{ experience.experience.experience_title }} · <span>{{experience.experience.place}}</span></p>
									<p class="mb-1 text-bold-md">{{ experience.experience.tag }}</p>
									<p class="mb-0 text-small-faint">USD {{ experience.experience.price }} per person</p>

									<div class="mb-0 mt-0 d-flex justify-content-between align-items-center">
										<span class="rateYo pl-0"><input type="hidden" value="{{ experience.experience.Weighted_Average }}" name="rateyoid" class="rateyoid"></span>
										<span class="review float-left" aria-label="{{ experience.experience.reviews_no }} reviews">
											<span class="reviews">{{ experience.experience.reviews_no }}</span>
										</span>
									</div>

								</div>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
		</section>
	{% endif %}
{% endblock %}

{% block sidebar %}
	<aside class="col-md-3 pt-3 d-none d-sm-none d-md-block">
			{% for advert in adverts %}
			<a href="{{ url_for('main.become_a_host')}}">
			<div class="mb-3 h-auto w-100">
				<img class="w-100 h-auto rounded d-block" src="{{ url_for('main.uploaded_advert', filename=advert.filename) }}" alt="">
			</div></a>
			{% endfor %}
	</aside>
{% endblock %}

{% block script %}

	<script src="zuck.js"></script>
	<script>

	   function buildItem(id, type, length, src, preview, link, linkText, seen, time){
	       return {
	                   "id": id,
	                   "type": type,
	                   "length": length,
	                   "src": src,
	                   "preview": preview,
	                   "link": link,
	                   "linkText": linkText,
	                   "seen": seen,
						"time": time
	               };
	   }

		function initDemo(stories_object){
			var header = document.getElementById("header");
			var skin = location.href.split('skin=')[1];
			
			if(!skin) {
				skin = 'Snapgram';
			} 

			if(skin.indexOf('#')!==-1){
			   skin = skin.split('#')[0];
			}

			var skins = {
				'Snapgram': {
					'avatars': true,
					'list': false,
					'autoFullScreen': false,
	                'cubeEffect': true
				},

				'VemDeZAP': {
					'avatars': false,
					'list': true,
					'autoFullScreen': false,
	                'cubeEffect': false
				},

				'FaceSnap': {
					'avatars': true,
					'list': false,
					'autoFullScreen': true,
	                'cubeEffect': false
				},

				'Snapssenger': {
					'avatars': false,
					'list': false,
					'autoFullScreen': false,
	                'cubeEffect': false
				}
			};
			
			var timeIndex = 0;
			var shifts = [35, 60, 60*3, 60*60*2, 60*60*25, 60*60*24*4, 60*60*24*10];
			var timestamp = function() {
			    var now = new Date();
			    var shift = shifts[timeIndex++] || 0;
			    var date = new Date( now - shift*1000);

			    return date.getTime() / 1000;
			};

			var n;
			var _stories = [];
			for (n = 0; n < stories_object.length; n++) {
				var _story =  {
								id: stories_object[n].name,
								photo: stories_object[n].link,
								name: stories_object[n].name,
								link: "",
								lastUpdated: timestamp(),
								items: [
									buildItem("item-" + n, "photo", 3, stories_object[n].link, "", '', false, false, timestamp())
									]
				};
				_stories.push(_story);
			};

			var stories = new Zuck('stories', {
				backNative: true,
	            previousTap: true,
				autoFullScreen: skins[skin]['autoFullScreen'],
				skin: skin,
				avatars: skins[skin]['avatars'],
				list: skins[skin]['list'],
	            cubeEffect: skins[skin]['cubeEffect'],
				localStorage: true,
				stories: _stories
			});
	       
	       var el = document.querySelectorAll('#skin option');
	       var total = el.length;
	       for (var i = 0; i < total; i++) {
				var what = (skin==el[i].value)?true:false;
	           
				if(what){
					el[i].setAttribute('selected', what);

					header.innerHTML = skin;
					header.className = skin;
				} else {
					el[i].removeAttribute('selected');
				}
	       }

			document.body.style.display = 'block';
		};

		get_stories();

		function get_stories(){
			$.ajax({
				url: '/api/v1/stories',
				type: 'GET',
				data: {
				},
				datatype: 'json',
				contentType: "application/json; charset=utf-8",
				success: function(data_result){
					//console.log(data_result);
					initDemo(data_result.stories);
				},
				error:function(data){
				}
			});
		}
	</script>
	<script>

		
		// corousel

	$('#tubayoCarousel').carousel({
	  interval: 10000
	})

	$('.carousel .carousel-item').each(function(){
	    var next = $(this).next();
	    if (!next.length) {
	    next = $(this).siblings(':first');
	    }
	    next.children(':first-child').clone().appendTo($(this));
	    
	    for (var i=0;i<2;i++) {
	        next=next.next();
	        if (!next.length) {
	        	next = $(this).siblings(':first');
	      	}
	        
	        next.children(':first-child').clone().appendTo($(this));
	      }
	});
	</script>
{% endblock %}

app/main/templates/main/shoppingcart.html
{% extends 'base.html' %}
{% set active_page = "cart" %}

{% block content%}
<main>
	<div class="container">
		<div class="card shopping-cart mt-5">
			<div class="card-header bg-dark text-light">
				<i class="fa fa-shopping-cart" aria-hidden="true"></i>
				Booking cart
				<a href=" {{ url_for('main.experience')}} " class="btn btn-outline-info btn-sm pull-right">Continue Booking</a>
				<div class="clearfix"></div>
			</div>
			<form action="" method="POST">
				<div class="card-body">
					<!-- PRODUCT -->
					{% for item in item %}
					<div class="row">
						<div class="col-12 col-sm-12 col-md-2 text-center">
							<img class="img-responsive img-fluid" src="{{ url_for('main.uploaded_experience', filename=item.filename) }}" alt="prewiew" height="80">
						</div>
						<div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
							<h4 class="product-name"><strong>{{ item.item_name }}</strong>
							<br>
							<span class="text-small">{{ moment(item.date).format('LL') }}</span>
							</h4>
							<h4>
								<small>{{ item.description }}</small>
							</h4>
						</div>
						<div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
							<div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
								<h4 class="text-small">price</h4>
								<h6><strong>{{ item.price }}<span class="text-muted">x</span></strong></h6>
							</div>
							<div class="col-4 col-sm-4 col-md-4">
								<h4 class="text-small">Number of people</h4>
								<div class="quantity">
								  <input name="quantity{{ loop.index }}" type="number" min="1" max="99" step="1" value="{{ item.quantity }}" inputmode="numeric" title="Number of people" size="4">
								</div>
							</div>
							<div class="col-2 col-sm-2 col-md-2 text-right">
								<a href='{{ url_for('main.remove_item', cartitem_id=item.id) }}' role="button" aria-pressed="true" class="btn btn-outline-danger btn-lg">
									<i class="fa fa-trash" aria-hidden="true"></i>
								</a>
							</div>
						</div>
					</div>
					<hr class="w-100">
					{% endfor %}
					<!-- END PRODUCT -->
					<div class="float-right my-2">
						<button class="btn btn-outline-primary float-right">
							Update shopping cart
						</button>
					</div>
				</div>
			</form>
			<div class="card-footer">
				<div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
					<div class="row">
						<div class="col-6">
							<input type="text" class="form-control" placeholder="coupon code">
						</div>
						<div class="col-6">
							<input type="submit" class="btn btn-default" value="Use coupon">
						</div>
					</div>
				</div>
				<div class="pull-right" style="margin: 10px">
					<a role="button" href="https://payments.pesapal.com/tubayo" target="_blank" class="btn btn-success pull-right">Checkout</a>
					<div class="pull-right" style="margin: 5px">
						Total price: <b>${{ total2[0][0] }}</b>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

{% block script %}
	<script>
		jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.quantity input');
		jQuery('.quantity').each(function() {
		  var spinner = jQuery(this),
		    input = spinner.find('input[type="number"]'),
		    btnUp = spinner.find('.quantity-up'),
		    btnDown = spinner.find('.quantity-down'),
		    min = input.attr('min'),
		    max = input.attr('max');

		  btnUp.click(function() {
		    var oldValue = parseFloat(input.val());
		    if (oldValue >= max) {
		      var newVal = oldValue;
		    } else {
		      var newVal = oldValue + 1;
		    }
		    spinner.find("input").val(newVal);
		    spinner.find("input").trigger("change");
		  });

		  btnDown.click(function() {
		    var oldValue = parseFloat(input.val());
		    if (oldValue <= min) {
		      var newVal = oldValue;
		    } else {
		      var newVal = oldValue - 1;
		    }
		    spinner.find("input").val(newVal);
		    spinner.find("input").trigger("change");
		  });

		});
	</script>
{% endblock %}